# [START gae_python37_cloudsql_config]
runtime: python39
env_variables:
  CLOUD_SQL_USERNAME: {PLACEHOLDER}
  CLOUD_SQL_PASSWORD: {PLACEHOLDER}
  CLOUD_SQL_CONNECTION_NAME: {PLACEHOLDER}
  CLOUD_SQL_DATABASE_NAME: {PLACEHOLDER}
  PROJECT_NAME: {PLACEHOLDER}
  ZONE: {PLACEHOLDER}
  LOCATION: {PLACEHOLDER}
  TOPIC_NAME : host_topic
  SUB_NAME : host_sub
# [END gae_python37_cloudsql_config]
